name: cpp_checks
on: [push]

jobs:
  check-clang-format:
    name: Clang format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: jidicula/clang-format-action@v4.11.0
      with:
        clang-format-version: '13'
        check-path: 'meta-das-core'
        fallback-style: 'Google'

  check-cppcheck:
    name: Cppcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Cppcheck
      run: sudo apt install cppcheck
    - name: Running Cppcheck
      run: find . -regex '.*\.\(cpp\|hpp\|c\|h\)' | xargs cppcheck
